import {
  bigserial,
  date,
  doublePrecision,
  integer,
  jsonb,
  numeric,
  pgTable,
  text,
  timestamp,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";

export const users = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  email: text("email").notNull().unique(),
  password: text("password").notNull(),
  phone: text("phone"),
  role: text("role").notNull().default("buyer"),
  domainLink: text("domain_link"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
  subscriptionStatus: text("subscription_status").notNull().default("free"),
});

export const landListings = pgTable("land_listings", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  url: text("url"),
  title: text("title"),
  price: numeric("price"),
  acres: numeric("acres"),
  latitude: doublePrecision("latitude"),
  longitude: doublePrecision("longitude"),
  address1: text("address1"),
  address2: text("address2"),
  city: text("city"),
  stateAbbreviation: varchar("state_abbreviation", { length: 10 }),
  stateName: text("state_name"),
  zip: varchar("zip", { length: 20 }),
  county: text("county"),
  baths: integer("baths"),
  beds: integer("beds"),
  propertyType: text("property_type").array(),
  externalLink: text("external_link"),
  listingDate: date("listing_date"),
  description: text("description").array(),
  directions: text("directions").array(),
  activities: text("activities").array(),
  propertyAmenities: jsonb("property_amenities"),
  photos: text("photos").array(),
  propertyMediaData: jsonb("property_media_data"),
  brokerUrl: text("broker_url"),
  brokerContactName: text("broker_contact_name"),
  brokerEmail: text("broker_email"),
  brokerPhoneNumbers: jsonb("broker_phone_numbers"),
  brokerCompanyAddress1: text("broker_company_address1"),
  brokerCompanyAddress2: text("broker_company_address2"),
  brokerCompanyName: text("broker_company_name"),
  brokerCompanyCity: text("broker_company_city"),
  brokerCompanyState: varchar("broker_company_state", { length: 10 }),
  brokerCompanyZip: varchar("broker_company_zip", { length: 20 }),
  brokerDescription: text("broker_description").array(),
  brokerExternalLink: text("broker_external_link"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});
